config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  devise_for :users
  resources :images
  resources :tags, only: [:new, :create, :index]
  resources :favors, only: [:new, :create]

  get 'recs' => 'recs#index'

  namespace :api do
    get '/images' => 'images#index'

  end

  get 'pages/caves'   => 'pages#cave'
  get 'pages/places'  => 'pages#place'
  get 'pages/islands' => 'pages#island'
end

app/models/cave.rb
class Cave < ActiveRecord::Base
end

app/models/favor.rb
class Favor < ActiveRecord::Base
  belongs_to :image
  belongs_to :user
end

app/models/homepage.rb
class Homepage < ActiveRecord::Base
end

app/models/image.rb
class Image < ActiveRecord::Base
  validates :photo, presence: true
  mount_uploader :photo, PhotoUploader
  belongs_to :user
  has_many :tags
  has_many :favors
end

app/models/island.rb
class Island < ActiveRecord::Base
end

app/models/place.rb
class Place < ActiveRecord::Base
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :image
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :images
  has_many :tags
  has_many :favors
end

app/controllers/api/images_controller.rb
class Api::ImagesController < ApplicationController

  def index
    @images = Image.all
    render json: @images
  end

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  @image = Image.new
end

app/controllers/favors_controller.rb
class FavorsController < ApplicationController
  def new
    image = Image.find(params[:image_id])
    @favor = image.favors.new
    @favor.user_id = current_user.id
  end
  
  def create
    @favor = Favor.new(params.require(:favor).permit(:image_id, :user_id))
    if @favor.save
      redirect_to images_path, notice: "Successfully Added"
    else
      render :new
    end
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  before_action :authenticate_user!
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
    @total = 0

    @image = current_user.images.new
    @favors = Favor.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new

    @image = current_user.images.new
  end

  # GET /images/1/edit
  def edit
    @image = Image.find(params[:id])
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to images_path, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    @image = Image.find(params[:id])
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:title, :photo, :user_id, :content)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    @homepages = Homepage.all
  end

  def cave
    @caves = Cave.all
  end

  def place
    @places = Place.all
  end

  def island
    @islands = Island.all
  end
end

app/controllers/recs_controller.rb
class RecsController < ApplicationController

    def index
        @favors = Favor.all
          @recs = []

           Tag.all.each do |tag|
            @recs << tag if tag.user_id != current_user.id
          end

           Favor.all.each do |favor|
             @recs << favor if favor.user_id != current_user.id
          end
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all
    @favors = Favor.all

    
    @favor = Favor.new


  end

  def new
    @image = Image.find(params[:id])
    @tag = @image.tags.new
  end

  def create
    @tag = Tag.new(params.require(:tag).permit(:image_id, :user_id))
    if @tag.save
      redirect_to images_path, notice: "Successfully Tag"
    else
      render :new
    end
  end

end

app/helpers/api/images_helper.rb
module Api::ImagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favors_helper.rb
module FavorsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/favors/create.html.erb
<h1>Favors#create</h1>
<p>Find me in app/views/favors/create.html.erb</p>

app/views/favors/new.html.erb
<h1>Favors Image</h1>

<%= image_tag @favor.image.photo.url(:large) %>

<%= simple_form_for @favor do |f| %>
  <%= f.association :image, :as => :hidden %>
  <%= f.association :user, :as => :hidden%><br>


  <%= f.submit "Favor", class: "btn btn-success" %>
<%end%>

app/views/images/_form.html.erb
<%= simple_form_for @image do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :title, input_html: { class: 'form-control' } %>
  <div class="field">
    <%= f.input :photo, input_html: { class: 'form-control' } %>
    <br>
  </div>

  <%= f.input :content %>

  <div class="field">
    <%= f.association :user, :as => :hidden %>
  </div>


  <div class="actions">
    <p>
      <%= f.submit class: 'btn btn-primary'  %>
    </p>
  </div>
<% end %>

app/views/images/_index.html.erb
  <% @links.each do |link| %>
    <% if current_user.id == link.user.id %>
        <div class="col-md-3">
          <%= link_to "#", data: {toggle: "modal", target: "#modal-image#{link.id}"} do %>
          <%= image_tag link.photo.url(:thumb)%>
          <%end%>


          <!-- Modal -->
          <div class="modal fade" id="modal-image<%= link.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                  <h4 class="modal-title" id="myModalLabel">Image <%= link.id %></h4>
                </div>
                <div class="modal-body">
                  <%= link_to tags_path(id: link.id) do %>
                    <%= image_tag link.photo.url(:large) %>
                  <%end%>

                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <a href="#" tabindex="0" class="btn btn-lg btn-success" role="button" data-toggle="popover" data-placement="top" data-trigger="focus" data-content="Click the photo to tag">Tag</a>
                  </div>
                 <br>
                </div>

              </div>
            </div>
          </div>

        </div>
      <%end%>
  <%end%>

app/views/images/_side.html.erb
<div class="col-md-4">
  <div class="image-box">
    <div class="image-box-inside">

        <% @favors.each do |favor| %>
          <% if favor.user_id == current_user.id %>




              <!-- Button trigger modal -->
                <%= link_to "#", data: {toggle: "modal", target: "#photo-modal#{favor.image.id}"} do %>
                  <%= image_tag favor.image.photo.url(:thumb), id: "image-on-side" %>
                <%end%>

              <!-- Modal -->
                  <div class="modal fade" id="photo-modal<%=favor.image.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                          <h4 class="modal-title" id="myModalLabel"><%= favor.image.title %></h4>
                        </div>
                        <div class="modal-body">
                          <%= link_to new_favor_path(image_id: favor.image.id, user_id: current_user.id) do %>
                            <%= image_tag favor.image.photo.url(:large), id: "image-in-modal" %>
                          <%end%>
                            <hr>
                          <p><%= favor.image.content %></p>
                        </div>
                         <div class="modal-footer">
                            <%= link_to "#", class: "btn btn-danger" do %>
                              Delete
                            <%end%>
                          </div>
                      </div>
                    </div>
                  </div>



          <%end%>
        <%end%>
    </div>
  </div>

  <%= render partial: "/images/ten" %>
</div>

app/views/images/_ten.html.erb
<br >
<div class="image-box">
  <div class="image-box-inside most-ten">
    <%= link_to "10 most beautiful places", "#" %><br>
    <%= link_to "10 most beautiful islands", "#" %><br>
    <%= link_to "10 most beautiful caves", "#" %><br>
    <%= link_to "10 most beautiful moutains", "#" %><br>
  </div>
</div>

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<button  class="btn btn-primary btn-lg" data-toggle="modal" data-target="#upload-image">
  Upload Image
</button>

<br><br>

<!-- Modal -->
<div class="modal fade" id="upload-image" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">New Photo</h4>
      </div>
      <div class="modal-body">
        <%= render partial: "form" %>
      </div>

    </div>
  </div>
</div>

<button class="btn btn-primary btn-lg favorite-button">Favorite image</button>


<div class="row">
  <div class="col-md-8">



      <div class="image-box">
        <div class="image-box-inside">

            <% @images.each do |image| %>

              <% if image.user.id == current_user.id %>

            <!-- Button trigger modal -->
              <%= link_to "#", data: {toggle: "modal", target: "#photo-modal#{image.id}"} do %>
                <%= image_tag image.photo.url(:thumb), id: "image-in-homepage" %>
              <%end%>

            <!-- Modal -->
                <div class="modal fade" id="photo-modal<%=image.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                        <h4 class="modal-title" id="myModalLabel"><%= image.title %></h4>
                      </div>
                      <div class="modal-body">
                        <%= link_to new_tag_path(id: image.id) do %>
                          <%= image_tag image.photo.url(:large), id: "image-in-modal" %>
                        <%end%>
                          <hr>
                        <p><%= image.content %></p>
                      </div>
                       <div class="modal-footer">
                         <a href="#" tabindex="0" class="btn btn-lg btn-success tag" role="button" data-toggle="popover" data-placement="top" data-trigger="focus" data-content="Click the photo to tag">Tag</a>
                         <%= link_to "Edit", edit_image_path(id: image.id), class:"btn btn-primary" %>
                         <%= link_to "Delete", image_path(id: image.id), method: :delete, data: {confirm: "Are you sure?"}, class:"btn btn-primary" %>


                       </div>
                    </div>
                  </div>
                </div>

              <%end%>
            <%end%>
          </div>
    </div>
  </div>

 <%= render partial: "side" %>
</div>

app/views/images/new.html.erb
<h1>New image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @image.title %>
</p>

<p>
  <strong>Photo:</strong>
  <%= image_tag @image.photo.url(:large) %>
</p>
<br>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Destroy', image_path(@image), method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', images_path %>

app/views/recs/index.html.erb
<h3 id="rec-page">Recommend Image</h3>

<button class="btn btn-primary btn-lg favorite-button">Favorite image</button>

<div class="row">
  <div class="col-md-8">
    <div class="image-box">
        <div class="image-box-inside">

          <% @recs.each do |rec| %>



              <!-- Button trigger modal -->
                <%= link_to "#", data: {toggle: "modal", target: "#photo-modal#{rec.image.id}"} do %>
                  <%= image_tag rec.image.photo.url(:thumb), id: "image-in-homepage" %>
                <%end%>

              <!-- Modal -->
                  <div class="modal fade" id="photo-modal<%=rec.image.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                          <h4 class="modal-title" id="myModalLabel"><%= rec.image.title %></h4>
                        </div>
                        <div class="modal-body">

                            <%= image_tag rec.image.photo.url(:large), id: "image-in-modal" %>

                            <hr>
                          <p><%= rec.image.content %></p>
                        </div>
                        <div class="modal-footer">

                        </div>
                      </div>
                    </div>
                  </div>



          <%end%>
        </div>
      </div>
    </div>
<%= render partial: "images/side" %>
</div>

app/views/tags/_favor.html.erb
<%= simple_form_for @favor do |f| %>
  <%= f.association :image  %>
  <%= f.association :user %><br>


  <%= f.submit "Favor", class: "btn btn-success" %>
<%end%>

app/views/tags/_tag.html.erb
<%= simple_form_for @tag do |f| %>
  <%= f.association :image, :as => :hidden %>
  <%= f.association :user, label_method: :email, value_method: :id, include_blank: false  %>

  <%= f.submit "Tag", class: "btn btn-success" %>
<%end%>

app/views/tags/index.html.erb
<h3 id="h3-in-big-box">Tag Image</h3>
<button class="btn btn-primary btn-lg favorite-button">Favorite image</button>
<div class="row">
  <div class="col-md-8">
    <div class="image-box">
        <div class="image-box-inside">

          <% @tags.each do |tag| %>
            <% if tag.user.id == current_user.id %>


              <!-- Button trigger modal -->
                <%= link_to "#", data: {toggle: "modal", target: "#photo-modal#{tag.image.id}"} do %>
                  <%= image_tag tag.image.photo.url(:thumb), id: "image-in-homepage" %>
                <%end%>

              <!-- Modal -->
                  <div class="modal fade" id="photo-modal<%=tag.image.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                          <h4 class="modal-title" id="myModalLabel"><%= tag.image.title %></h4>
                        </div>
                        <div class="modal-body">
                          <%= link_to new_favor_path(image_id: tag.image.id, user_id: current_user.id) do %>
                            <%= image_tag tag.image.photo.url(:large), id: "image-in-modal" %>
                          <%end%>
                            <hr>
                          <p><%= tag.image.content %></p>
                          <%= render partial: "favor" %>
                        </div>
                        <div class="modal-footer">
                          <a href="#" tabindex="0" class="btn btn-lg btn-success favorite" role="button" data-toggle="popover" data-placement="top" data-trigger="focus" data-content="Click the photo to favorite">Favorite</a>

                        </div>
                      </div>
                    </div>
                  </div>




            <%end%>
          <%end%>
        </div>
      </div>
    </div>
<%= render partial: "images/side" %>
</div>

app/views/tags/new.html.erb
<h1>Tags</h1>

<%= image_tag @image.photo %>
<%= render partial: "tag" %>