config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  devise_for :users
  resources :images
  resources :tags, only: [:new, :create, :index]
  resources :favors, only: [:new, :create]

  get 'recs' => 'recs#index'

  namespace :api do
    get '/images' => 'images#index'

  end

  get 'pages/caves'   => 'pages#cave'
  get 'pages/places'  => 'pages#place'
  get 'pages/islands' => 'pages#island'
end

app/models/cave.rb
class Cave < ActiveRecord::Base
end

app/models/favor.rb
class Favor < ActiveRecord::Base
  belongs_to :image
  belongs_to :user
end

app/models/homepage.rb
class Homepage < ActiveRecord::Base
end

app/models/image.rb
class Image < ActiveRecord::Base
  validates :photo, presence: true
  mount_uploader :photo, PhotoUploader
  belongs_to :user
  has_many :tags
  has_many :favors
end

app/models/island.rb
class Island < ActiveRecord::Base
end

app/models/place.rb
class Place < ActiveRecord::Base
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :image
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :images
  has_many :tags
  has_many :favors
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  @image = Image.new
end

app/controllers/favors_controller.rb
class FavorsController < ApplicationController
  def new
    image = Image.find(params[:image_id])
    @favor = image.favors.new
    @favor.user_id = current_user.id
  end
  
  def create
    @favor = Favor.new(params.require(:favor).permit(:image_id, :user_id))
    if @favor.save
      redirect_to images_path, notice: "Successfully Added"
    else
      render :new
    end
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  before_action :authenticate_user!
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
    @total = 0

    @image = current_user.images.new
    @favors = Favor.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new

    @image = current_user.images.new
  end

  # GET /images/1/edit
  def edit
    @image = Image.find(params[:id])
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to images_path, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    @image = Image.find(params[:id])
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:title, :photo, :user_id, :content)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    @homepages = Homepage.all
  end

  def cave
    @caves = Cave.all
  end

  def place
    @places = Place.all
  end

  def island
    @islands = Island.all
  end
end

app/controllers/recs_controller.rb
class RecsController < ApplicationController

    def index
        @favors = Favor.all
          @recs = []

           Tag.all.each do |tag|
            @recs << tag if tag.user_id != current_user.id
          end

           Favor.all.each do |favor|
             @recs << favor if favor.user_id != current_user.id
          end
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all
    @favors = Favor.all

    
    @favor = Favor.new


  end

  def new
    @image = Image.find(params[:id])
    @tag = @image.tags.new
  end

  def create
    @tag = Tag.new(params.require(:tag).permit(:image_id, :user_id))
    if @tag.save
      redirect_to images_path, notice: "Successfully Tag"
    else
      render :new
    end
  end

end

app/helpers/api/images_helper.rb
module Api::ImagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favors_helper.rb
module FavorsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ImagesCloset</title>
  <link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>

    <script src="//code.jquery.com/jquery-2.1.1.min.js"></script>

  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag "application" %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1">

</head>
  <body>
      <div id="wrapper">
        <div class="navbar navbar-default navbar-static-top">
              <div class="container">
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-ex-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                  <%= link_to "ImagesCloset", root_path, class: "navbar-brand" %>
                </div>
                <div class="collapse navbar-collapse" id="navbar-ex-collapse">
                  <ul class="nav navbar-nav navbar-right">
                    <% if user_signed_in? %>
                      <li><%= link_to "My Page", images_path, class: "btn btn-primary log-in" %></li>
                      <li><%= link_to "Tag Image", tags_path, class: "btn btn-primary log-in" %></li>
                      <li><%= link_to "Recommend", recs_path, class: "btn btn-primary log-in" %></li>
                      <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-primary log-in" %></li>
                    <%else%>
                      <li><%= link_to "Sign In", new_user_session_path, class: "btn btn-primary log-in" %></li>
                      <li><%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary log-in" %></li>
                    <%end%>
                  </ul>
                </div>
              </div>
        <div class="container">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/pages/_tenside.html.erb
<div class="image-box">
  <div class="image-box-inside most-ten">
    <%= link_to "20 most beautiful places", pages_places_path %><br>
    <%= link_to "20 most beautiful islands", pages_islands_path %><br>
    <%= link_to "20 most beautiful caves", pages_caves_path %><br>
    <%= link_to "20 most beautiful moutains", "#" %><br>
  </div>
</div>

app/views/pages/cave.html.erb
<div class="row homepage">
  <div class="col-md-8">



      <div class="image-box img-responsive text-center">
        <div class="image-box-inside">

            <% @caves.each do |image| %>



                <!-- Button trigger modal -->
                  <%= link_to "#", data: {toggle: "modal", target: "#photo-modal#{image.id}"} do %>
                    <%= image_tag image.photo, id: "image-in-homepage" %>
                  <%end%>

                <!-- Modal -->
                    <div class="modal fade" id="photo-modal<%=image.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                      <div class="modal-dialog">
                        <div class="modal-content">
                          <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                            <h4 class="modal-title" id="myModalLabel"><%= image.title %></h4>
                          </div>
                          <div class="modal-body">
                              <%= image_tag image.photo, id: "image-in-modal" %>
                              <hr>
                            <p><%= image.content %></p>
                          </div>

                        </div>
                      </div>
                    </div>

            <%end%>
        </div>
    </div>
  </div>
  <div class="col-md-4">

    <%= render partial: "tenside" %>
    </div>


</div>

app/views/pages/index.html.erb
<div class="row homepage">
  <div class="col-md-8">



    <div class="image-box img-responsive text-center">
      <div class="image-box-inside">

        <% @homepages.each do |image| %>



        <!-- Button trigger modal -->
        <%= link_to "#", data: {toggle: "modal", target: "#photo-modal#{image.id}"} do %>
        <%= image_tag image.photo, id: "image-in-homepage" %>
        <%end%>

        <!-- Modal -->
        <div class="modal fade" id="photo-modal<%=image.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel"><%= image.title %></h4>
              </div>
              <div class="modal-body">
                <%= image_tag image.photo, id: "image-in-modal" %>
                <hr>
                <p><%= image.content %></p>
              </div>

            </div>
          </div>
        </div>

        <%end%>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="image-box">
      <div class="image-box-inside welcome-box">
        <h3>Welcome</h3>
        <p>
          These are indeed world’s most famous photos. Every single one of them has a great story behind, we’re trying to bring you the pictures that changed mankind. If the change was good or bad, that is for you to judge. Click it to see more information.
        </p>
      </div>
    </div>
    <br >
    <div class="image-box">
      <div class="image-box-inside most-ten">
        <%= link_to "20 most beautiful places", pages_places_path %><br>
        <%= link_to "20 most beautiful islands", pages_islands_path %><br>
        <%= link_to "20 most beautiful caves", pages_caves_path %><br>
        <%= link_to "20 most beautiful moutains", "#" %><br>
      </div>
    </div>


  </div>

app/views/pages/island.html.erb
<div class="row homepage">
  <div class="col-md-8">



      <div class="image-box img-responsive text-center">
        <div class="image-box-inside">

            <% @islands.each do |image| %>



                <!-- Button trigger modal -->
                  <%= link_to "#", data: {toggle: "modal", target: "#photo-modal#{image.id}"} do %>
                    <%= image_tag image.photo, id: "image-in-homepage" %>
                  <%end%>

                <!-- Modal -->
                    <div class="modal fade" id="photo-modal<%=image.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                      <div class="modal-dialog">
                        <div class="modal-content">
                          <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                            <h4 class="modal-title" id="myModalLabel"><%= image.title %></h4>
                          </div>
                          <div class="modal-body">
                              <%= image_tag image.photo, id: "image-in-modal" %>
                              <hr>
                            <p><%= image.content %></p>
                          </div>

                        </div>
                      </div>
                    </div>

            <%end%>
        </div>
    </div>
  </div>
  <div class="col-md-4">

    <%= render partial: "tenside" %>
    </div>


</div>

app/views/pages/place.html.erb
<div class="row homepage">
  <div class="col-md-8">



      <div class="image-box">
        <div class="image-box-inside">

            <% @places.each do |image| %>



                <!-- Button trigger modal -->
                  <%= link_to "#", data: {toggle: "modal", target: "#photo-modal#{image.id}"} do %>
                    <%= image_tag image.photo, id: "image-in-homepage" %>
                  <%end%>

                <!-- Modal -->
                    <div class="modal fade" id="photo-modal<%=image.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                      <div class="modal-dialog">
                        <div class="modal-content">
                          <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                            <h4 class="modal-title" id="myModalLabel"><%= image.title %></h4>
                          </div>
                          <div class="modal-body">
                              <%= image_tag image.photo, id: "image-in-modal" %>
                              <hr>
                            <p><%= image.content %></p>
                          </div>

                        </div>
                      </div>
                    </div>

            <%end%>
        </div>
    </div>
  </div>
  <div class="col-md-4">

    <%= render partial: "tenside" %>
    </div>


</div>